[project]
name = "mstat-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "altair>=6.0.0",
    "dagster>=1.13.2",
    "dash>=4.1.0",
    "dbt-core>=1.11.7",
    "dbt-postgres>=1.10.0",
    "ltsa",
    "matplotlib>=3.10.9",
    "nibabel>=5.4.2",
    "numpy>=2.4.2",
    "patito>=0.8.6",
    "plotly>=6.7.0",
    "polars>=1.38.1",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.49",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "pytest>=9.0.2",
    "ruff>=0.15.5",
    "ty>=0.0.21",
]

[tool.uv.workspace]
members = [
    "packages/*",
]

[tool.uv.sources]
ltsa = { workspace = true }

[tool.ty.src]
exclude = ["tests"]
