WITH casted AS (
    SELECT
        {{ norm_text_codes('"PHASE"', to_upper=true) }}::TEXT AS study_phase,
        {{ norm_text_codes('"PTID"', to_upper=true) }}::TEXT AS ptid,
        {{ norm_text_codes('"RID"') }}::INTEGER AS roster_id,
        {{ norm_text_codes('"VISCODE"', to_upper=true) }}::TEXT AS visit_code_1,
        {{ norm_text_codes('"VISCODE2"', to_upper=true) }}::TEXT AS visit_code_2,
        NULLIF(TRIM("VISDATE"::TEXT), '')::DATE AS visit_date,
        {{ norm_text_codes('"PTSOURCE"') }}::INTEGER AS participant_source_code,
        {{ norm_text_codes('"PTGENDER"') }}::INTEGER AS gender_code,
        {{ norm_text_codes('"PTDOB"') }}::TEXT AS birth_month_year,
        EXTRACT(YEAR FROM NULLIF(TRIM("PTDOBYY"::TEXT), '')::DATE)::INTEGER AS birth_year,
        {{ norm_text_codes('"PTHAND"') }}::INTEGER AS handedness_code,
        {{ norm_text_codes('"PTMARRY"') }}::INTEGER AS marital_status_code,
        {{ norm_text_codes('"PTEDUCAT"') }}::INTEGER AS education_years,
        {{ norm_text_codes('"PTWORKHS"') }}::INTEGER AS work_history_code,
        {{ norm_text_codes('"PTWORK"') }}::INTEGER AS occupation_code,
        {{ norm_text_codes('"PTNOTRT"') }}::INTEGER AS not_retired_code,
        {{ norm_text_codes('"PTRTYR"') }}::INTEGER AS retirement_year,
        {{ norm_text_codes('"PTHOME"') }}::INTEGER AS home_status_code,
        {{ norm_text_codes('"PTTLANG"') }}::INTEGER AS primary_language_code,
        {{ norm_text_codes('"PTPLANG"') }}::INTEGER AS preferred_language_code,
        {{ norm_text_codes('"PTADBEG"') }}::INTEGER AS alzheimers_symptom_onset_year,
        {{ norm_text_codes('"PTCOGBEG"') }}::INTEGER AS cognitive_symptom_onset_year,
        {{ norm_text_codes('"PTADDX"') }}::INTEGER AS alzheimers_diagnosis_year,
        {{ norm_text_codes('"PTETHCAT"') }}::INTEGER AS ethnicity_code,
        {{ norm_text_codes('"PTRACCAT"') }}::INTEGER AS race_code,
        {{ norm_text_codes('"PTIDENT"') }}::INTEGER AS identity_code,
        {{ norm_text_codes('"PTORIENT"') }}::INTEGER AS orientation_code,
        {{ norm_text_codes('"PTORIENTOT"') }}::INTEGER AS orientation_other_code,
        {{ norm_text_codes('"PTENGSPK"') }}::INTEGER AS english_speaking_code,
        {{ norm_text_codes('"PTNLANG"') }}::INTEGER AS native_language_code,
        {{ norm_text_codes('"PTENGSPKAGE"') }}::INTEGER AS english_speaking_age,
        {{ norm_text_codes('"PTCLANG"') }}::INTEGER AS current_language_code,
        {{ norm_text_codes('"PTLANGSP"') }}::INTEGER AS overall_speaking_ability_code,
        {{ norm_text_codes('"PTLANGWR"') }}::INTEGER AS overall_writing_ability_code,
        {{ norm_text_codes('"PTSPTIM"') }}::INTEGER AS spanish_speaking_time_percent,
        {{ norm_text_codes('"PTSPOTTIM"') }}::INTEGER AS spanish_other_language_time_percent,
        {{ norm_text_codes('"PTLANGPR1"') }}::INTEGER AS language_1_priority_code,
        {{ norm_text_codes('"PTLANGSP1"') }}::INTEGER AS language_1_speaking_ability_code,
        {{ norm_text_codes('"PTLANGRD1"') }}::INTEGER AS language_1_reading_ability_code,
        {{ norm_text_codes('"PTLANGWR1"') }}::INTEGER AS language_1_writing_ability_code,
        {{ norm_text_codes('"PTLANGUN1"') }}::INTEGER AS language_1_understanding_ability_code,
        {{ norm_text_codes('"PTLANGPR2"') }}::INTEGER AS language_2_priority_code,
        {{ norm_text_codes('"PTLANGSP2"') }}::INTEGER AS language_2_speaking_ability_code,
        {{ norm_text_codes('"PTLANGRD2"') }}::INTEGER AS language_2_reading_ability_code,
        {{ norm_text_codes('"PTLANGWR2"') }}::INTEGER AS language_2_writing_ability_code,
        {{ norm_text_codes('"PTLANGUN2"') }}::INTEGER AS language_2_understanding_ability_code,
        {{ norm_text_codes('"PTLANGPR3"') }}::INTEGER AS language_3_priority_code,
        {{ norm_text_codes('"PTLANGSP3"') }}::INTEGER AS language_3_speaking_ability_code,
        {{ norm_text_codes('"PTLANGRD3"') }}::INTEGER AS language_3_reading_ability_code,
        {{ norm_text_codes('"PTLANGWR3"') }}::INTEGER AS language_3_writing_ability_code,
        {{ norm_text_codes('"PTLANGUN3"') }}::INTEGER AS language_3_understanding_ability_code,
        {{ norm_text_codes('"PTLANGPR4"') }}::INTEGER AS language_4_priority_code,
        {{ norm_text_codes('"PTLANGSP4"') }}::INTEGER AS language_4_speaking_ability_code,
        {{ norm_text_codes('"PTLANGRD4"') }}::INTEGER AS language_4_reading_ability_code,
        {{ norm_text_codes('"PTLANGWR4"') }}::INTEGER AS language_4_writing_ability_code,
        {{ norm_text_codes('"PTLANGUN4"') }}::INTEGER AS language_4_understanding_ability_code,
        {{ norm_text_codes('"PTLANGPR5"') }}::INTEGER AS language_5_priority_code,
        {{ norm_text_codes('"PTLANGSP5"') }}::INTEGER AS language_5_speaking_ability_code,
        {{ norm_text_codes('"PTLANGRD5"') }}::INTEGER AS language_5_reading_ability_code,
        {{ norm_text_codes('"PTLANGWR5"') }}::INTEGER AS language_5_writing_ability_code,
        {{ norm_text_codes('"PTLANGUN5"') }}::INTEGER AS language_5_understanding_ability_code,
        {{ norm_text_codes('"PTLANGPR6"') }}::INTEGER AS language_6_priority_code,
        {{ norm_text_codes('"PTLANGSP6"') }}::INTEGER AS language_6_speaking_ability_code,
        {{ norm_text_codes('"PTLANGRD6"') }}::INTEGER AS language_6_reading_ability_code,
        {{ norm_text_codes('"PTLANGWR6"') }}::INTEGER AS language_6_writing_ability_code,
        {{ norm_text_codes('"PTLANGUN6"') }}::INTEGER AS language_6_understanding_ability_code,
        {{ norm_text_codes('"PTLANGTTL"') }}::INTEGER AS language_count,
        {{ norm_text_codes('"PTETHCATH"') }}::INTEGER AS hispanic_ethnicity_code,
        {{ norm_text_codes('"PTASIAN"') }}::INTEGER AS asian_subgroup_code,
        {{ norm_text_codes('"PTOPI"') }}::INTEGER AS pacific_islander_subgroup_code,
        {{ norm_text_codes('"PTBORN"') }}::INTEGER AS was_born_in_us_code,
        {{ norm_text_codes('"PTBIRPL"') }}::INTEGER AS birthplace_code,
        {{ norm_text_codes('"PTIMMAGE"') }}::INTEGER AS immigration_age,
        {{ norm_text_codes('"PTIMMWHY"') }}::TEXT AS immigration_reason_codes,
        {{ norm_text_codes('"PTBIRPR"') }}::INTEGER AS birthplace_region_code,
        {{ norm_text_codes('"PTBIRGR"') }}::INTEGER AS grew_up_region_code,
        {{ norm_text_codes('"ID"') }}::INTEGER AS record_id,
        {{ norm_text_codes('"SITEID"') }}::INTEGER AS site_id,
        NULLIF(TRIM("USERDATE"::TEXT), '')::TIMESTAMP AS record_created,
        NULLIF(TRIM("USERDATE2"::TEXT), '')::TIMESTAMP AS record_last_updated,
        {{ norm_text_codes('"DD_CRF_VERSION_LABEL"', to_upper=true) }}::TEXT AS crf_version_label,
        {{ norm_text_codes('"LANGUAGE_CODE"', to_upper=true) }}::TEXT AS language_code,
        {{ norm_text_codes('"HAS_QC_ERROR"') }}::INTEGER::BOOL AS has_qc_error,
        NULLIF(TRIM("update_stamp"::TEXT), '')::TIMESTAMP AS update_stamp
    FROM {{ ref('ptdemog') }}
),

new_viscodes AS (
    SELECT
        *,
        COALESCE(visit_code_2, visit_code_1) AS visit_code_final
    FROM casted
),

normed AS (
    SELECT
        *,
        {{ norm_viscodes('visit_code_final') }} AS visit_code_normed
    FROM new_viscodes
)

SELECT
    study_phase,
    ptid,
    roster_id,
    visit_code_normed,
    visit_date,
    participant_source_code,
    gender_code,
    birth_month_year,
    birth_year,
    handedness_code,
    marital_status_code,
    education_years,
    work_history_code,
    occupation_code,
    not_retired_code,
    retirement_year,
    home_status_code,
    primary_language_code,
    preferred_language_code,
    alzheimers_symptom_onset_year,
    cognitive_symptom_onset_year,
    alzheimers_diagnosis_year,
    ethnicity_code,
    race_code,
    identity_code,
    orientation_code,
    orientation_other_code,
    english_speaking_code,
    native_language_code,
    english_speaking_age,
    current_language_code,
    overall_speaking_ability_code,
    overall_writing_ability_code,
    spanish_speaking_time_percent,
    spanish_other_language_time_percent,
    language_1_priority_code,
    language_1_speaking_ability_code,
    language_1_reading_ability_code,
    language_1_writing_ability_code,
    language_1_understanding_ability_code,
    language_2_priority_code,
    language_2_speaking_ability_code,
    language_2_reading_ability_code,
    language_2_writing_ability_code,
    language_2_understanding_ability_code,
    language_3_priority_code,
    language_3_speaking_ability_code,
    language_3_reading_ability_code,
    language_3_writing_ability_code,
    language_3_understanding_ability_code,
    language_4_priority_code,
    language_4_speaking_ability_code,
    language_4_reading_ability_code,
    language_4_writing_ability_code,
    language_4_understanding_ability_code,
    language_5_priority_code,
    language_5_speaking_ability_code,
    language_5_reading_ability_code,
    language_5_writing_ability_code,
    language_5_understanding_ability_code,
    language_6_priority_code,
    language_6_speaking_ability_code,
    language_6_reading_ability_code,
    language_6_writing_ability_code,
    language_6_understanding_ability_code,
    language_count,
    hispanic_ethnicity_code,
    asian_subgroup_code,
    pacific_islander_subgroup_code,
    was_born_in_us_code,
    birthplace_code,
    immigration_age,
    immigration_reason_codes,
    birthplace_region_code,
    grew_up_region_code,
    record_id,
    site_id,
    record_created,
    record_last_updated,
    crf_version_label,
    language_code,
    has_qc_error,
    update_stamp
FROM normed
